import { loadEnv } from "./_bootstrap"; loadEnv();
import { getSpec, upsertSpec } from "../src/lib/specs-table";
const WS="fdc11e10-b89f-4989-8b73-ed6526c4d906";
const SLUG="dahlia-researches-from-winners-flow-ad-library";
(async()=>{
  const s:any=await getSpec(WS,SLUG);
  const summary=s.summary+" **INTENT-AWARE (not blind on temperature):** every creative task carries a declared intent `{ audience_temperature: cold|warm|hot, purpose: test-to-find-winner }`. Dahlia declares it FIRST ('I need a cold-audience ad for a test campaign'), then selects competitor WINNERS appropriate for that temperature and builds the ad for it; Max grades AGAINST the same declared intent (did she pick a good COLD-audience competitor? is it a scroll-stopping, consumer-psychology-powered COLD ad?). Ties into the dahlia goal's `audience_temperature` + cold-offer gate.";
  const phases=(s.phases||[]).map((p:any)=>({position:p.position,title:p.title,status:p.status,body:p.body,why:p.why,what:p.what,verification:p.verification}));
  // enrich Phase 1 (intent-scoped selection) + Phase 2 (intent-aware grading)
  const p1=phases.find((p:any)=>p.position===1); if(p1){ p1.body="Dahlia declares the creative INTENT first — `{audience_temperature, purpose:test-to-find-winner}` — then her research/angle-selection reads the winners-flow library SCOPED to that temperature (a cold-audience task prefers cold-appropriate winner concepts). Rank by winner_tier/composite, read concept_tags as the imitation rubric. Lane-agnostic."; p1.what="Add the declared-intent envelope to the creative task; point creative-agent.ts/creative-brief.ts angle/brief construction at the intent-scoped winner concepts (winner_tier + concept_tags), preferring temperature-appropriate winners."; }
  const p2=phases.find((p:any)=>p.position===2); if(p2){ p2.body="Max's QA grades each Dahlia creative AGAINST the declared intent — competitor selection (good pick FOR this temperature?), temperature selection (does the creative actually fit the declared temperature?), creative quality, scroll-stopping, DR/consumer-psychology — using the winner-library breakdown as the benchmark. NOT blind: the declared audience_temperature is passed to the grader so a cold ad is judged as a cold ad."; p2.what="Pass the declared intent (audience_temperature + purpose) into Max's QA/QC pass; score the 5-axis rubric intent-aware (each 1-10 + reason), persist to the grade ledger; lane-agnostic."; p2.verification="vitest: a QA pass over a fixture creative with a declared 'cold' intent emits all 5 rubric axes intent-aware (grades competitor + temperature FIT against 'cold') with scores + reasons and writes one grade row; `npx tsc --noEmit` clean."; }
  const res=await upsertSpec(WS,{ slug:SLUG, title:s.title, summary, owner:s.owner, parent:s.parent, parent_kind:"mandate", parent_ref:"growth#ad-creative-dahlia-under-max-beside-bianca", priority:s.priority, deferred:true, intended_status:"planned", intended_status_set_by:"ceo:dylan", auto_build:false, milestone_id:null, why:s.why, what:s.what }, phases as any);
  console.log("intent-awareness woven in · phases:", JSON.stringify(Object.keys(res.phase_ids)));
})().then(()=>process.exit(0)).catch(e=>{console.error(e.message);process.exit(1);});
