import { loadEnv } from "./_bootstrap";
loadEnv();
import { authorSpecRowStructured } from "../src/lib/author-spec";
const WS = "fdc11e10-b89f-4989-8b73-ed6526c4d906";
async function main() {
  const ok = await authorSpecRowStructured(WS, "carrie-reuse-existing-media", {
    title: "Carrie — reuse existing product media before flagging a real-asset gap",
    why: "Carrie ([[../specs/carrie-dr-content]]) over-flagged on the first real lander: she asked the founder to supply a before/after transformation and press logos that Amazing Coffee ALREADY had in product_media — but her lookup only checked the new `category` column, and all the legacy assets (`before`/`after` slots, `press_1..4` ABC/NBC/CBS/FOX, endorsement + ingredient shots) predate that column so their category was null and she couldn't see them. The founder had to point them out one by one. She must find what we already have — by slot/alt, not just category — so she only ever asks for genuinely-missing assets. (The catalog's categories were just backfilled from slot semantics, so category is now populated too.)",
    what: "Before opening a real-evidence content gap, Carrie's lane looks up existing product_media for the product that fits the slot — matching on category (now backfilled) AND slot/alt_text semantics — and REUSES a suitable asset instead of flagging it. She only opens a gap when no real asset exists. A real-evidence slot is NEVER satisfied by a source='generated' (AI) image — the never-fabricate-a-customer-result rule holds.",
    summary: "A precision fix to [[../libraries/builder-worker]] `runDrContentJob`. For each real-evidence image slot (before_after | ugc | testimonial_photo | press_logo), before opening a [[../tables/lander_content_gaps]] row, query the product's [[../tables/product_media]] for a suitable existing asset: match by `category` = the slot's asset_role, ELSE by slot/alt_text semantics (`before`/`after`→before_after, `press_*`→press_logo, `endorsement_*_avatar`→testimonial_photo, etc.) for any still-uncategorized rows — and REQUIRE `source <> 'generated'` (an AI image can't stand in as real customer/press evidence). If a match is found, reference it in the blueprint `content` bucket and DON'T open a gap; only open a gap when nothing real exists. Keeps Carrie's compliance line intact (she never fabricates a customer result — she just stops re-asking for assets we already own). Net: on the Amazing-Coffee blueprint she'd have opened 2 gaps (cert badges, UGC) instead of 4.",
    owner: "growth",
    parent: "[[../functions/growth#dr-content-fill]] — the DR-content fill mandate (Carrie, downstream of Cleo): a precision fix so Carrie reuses existing product media before flagging a gap (Growth operates; Ada/Platform builds — [[../functions/platform]]).",
    blocked_by: [],
    phases: [
      { title: "Reuse existing media by category + slot/alt before opening a gap", why: "Carrie must not ask the founder for a before/after or press logos we already have — she needs to actually look at existing product_media, not just the new category column.", what: "In runDrContentJob, add a real-asset lookup (category + slot/alt semantics, source<>generated) per real-evidence slot; reuse a match, else open a gap.", status: "planned",
        body: "In [[../libraries/builder-worker]] `runDrContentJob`, add a helper `findExistingRealAsset(productId, assetRole)` (in [[../libraries/lander-blueprints]] SDK) that queries [[../tables/product_media]] for the product where `source <> 'generated'` AND (`category` = the assetRole OR a slot/alt_text semantic match for the role — `before_after`←slot `before`/`after`, `press_logo`←slot `press_*`, `testimonial_photo`←`endorsement_*_avatar`, `ugc`←ugc/selfie/customer alt), returning the best candidate (prefer a categorized match, then a slot match). In Carrie's per-slot loop, for a REAL-evidence slot: call it FIRST — on a hit, write the media ref into the blueprint `content` bucket for that block and skip the gap; on a miss, open the [[../tables/lander_content_gaps]] row as today. Never let a `source='generated'` row satisfy a real-evidence slot (the compliance rule). Update the [[../recipes/dr-content]] skill wording. Probe product_media (database-is-the-spec).",
        verification: "Re-running Carrie on an Amazing-Coffee-style blueprint (a product that already has `before`/`after` + `press_*` media, categorized OR by slot) opens gaps ONLY for the genuinely-missing assets (e.g. certification badges + a UGC selfie) — NOT for before/after or press logos, which are reused from product_media and referenced in the content bucket. A `source='generated'` image is never used to satisfy a real-evidence slot. tsc clean.",
        verification_checks: undefined },
      { title: "Brain page", why: "CLAUDE.md hard rule + the reuse rule belongs on Carrie's page.", what: "Document the reuse-before-flag rule.", status: "planned",
        body: "Update `docs/brain/libraries/builder-worker.md` (Carrie's dr-content lane) + the [[../recipes/dr-content]] recipe with the reuse-existing-media rule (category + slot/alt match, source<>generated) and the never-fabricate guard. brain:index reconcile.",
        verification: "The brain/recipe pages document reuse-before-flag with the source<>generated guard. brain:index reconcile clean. tsc clean." }
    ],
  }, "planned", { intendedStatusSetBy: "ceo" });
  console.log(ok ? "authored carrie-reuse-existing-media" : "author failed");
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
