import { loadEnv } from "./_bootstrap"; loadEnv();
import { authorSpecRowStructured } from "../src/lib/author-spec";
const WS="fdc11e10-b89f-4989-8b73-ed6526c4d906";
async function main(){
  const a = await authorSpecRowStructured(WS, "pia-decomposition-emits-plain-slug-blocked-by", {
    title: "Pia's goal decomposition emits plain-slug blocked_by, not a namespaced goalSlug:specSlug the gating can't parse",
    why: "When Pia decomposed the Sol goal she wrote each member's blocked_by as a namespaced string like 'sol-ticket-direction-then-cheap-execution:sol-ticket-direction-artifact-and-first-touch-box-session'. But the build-gating resolves blockers with areGoalMates over PLAIN spec slugs and never splits on ':' — so the namespaced entry matched no spec, the blocker didn't resolve, and the M2 spec (sol-cheap-execution) built BEFORE its M1 dependency shipped. M1 creates the Direction table's migration, so M2's branch didn't have it and the table-refs guard correctly failed the build. Every future goal Pia plans would hit the same out-of-order builds. The dependency graph she produces is correct; only the blocked_by FORMAT is wrong.",
    what: "Pia's decomposition writes blocked_by as plain spec slugs (the format the build-gating enforces), so goal-member dependencies are honored at claim/build time and members build in topological order.",
    summary: "**Brain refs:** [[../libraries/agent-jobs]] [[../libraries/specs-table]]. Grounded in the 2026-07-07 Sol-goal build: sol-cheap-execution-over-ticket-direction built before sol-ticket-direction-artifact because blocked_by was 'goalSlug:specSlug' but agent-jobs.ts gating (areGoalMates, no split(':')) expects plain slugs. Fix at the Pia decomposition write-path + a validation of existing goal-member blocked_by.",
    owner: "platform",
    parent: '[[../functions/platform]] — "Autonomous build platform" mandate: a planned goal-member spec\'s blocked_by must be in the format the build-gating enforces, so members build in dependency order — never out of order because of a format the resolver can\'t parse.',
    blocked_by: [],
    phases: [
      { title: "Phase 1 — Pia writes plain-slug blocked_by", why: "The gating resolves plain spec slugs; a namespaced string never matches, so the blocker silently doesn't hold.", what: "Pia's plan-to-spec write emits blocked_by as plain spec slugs (strip any goal-slug prefix).", body: "In the Pia decomposition write path (the plan job → spec authoring), emit blocked_by entries as the bare member spec slug, not 'goalSlug:specSlug'. Cite the plan write-path + the areGoalMates gate in [[../libraries/agent-jobs]].", verification: "A goal Pia decomposes produces member specs whose blocked_by are plain spec slugs; the build-gating holds a dependent member until its blocker ships (no out-of-order build). A member with a satisfied blocker builds; one with an unshipped blocker is held.", status: "planned" },
      { title: "Phase 2 — validate/repair existing goal-member blocked_by", why: "Already-authored goal members (and any legacy) may carry the bad format; a check catches it before it causes another out-of-order build.", what: "A validation (and one-time repair) that goal-member blocked_by entries resolve to real sibling spec slugs, flagging/fixing any namespaced ones.", body: "Add a validation that every goal-member blocked_by entry resolves to an existing spec slug in the same goal; repair the Sol-goal members already fixed by hand and flag any future drift. Cite specs-table blocked_by + the goal-mate resolver.", verification: "The validation flags a namespaced/unresolvable blocked_by; the Sol-goal members pass; a repaired member's blocker holds correctly.", status: "planned" },
    ],
  }, "planned", { intendedStatusSetBy: "ceo", parentKind: "mandate", parentRef: "platform#build" });
  console.log("pia-blocked-by spec:", a?"authored":"FAILED");

  const b = await authorSpecRowStructured(WS, "builder-persona-add-upserts-by-key-and-generates-avatar", {
    title: "The builder upserts a persona by key + auto-generates its avatar — no duplicate keys, no imageless agents",
    why: "When a box-agent spec's build adds an org persona, the builder does it badly two ways. First, it INSERTS a new key even when one already exists — the prompt-auto-review build added a 'Prue' prompt-review entry on top of the existing one, producing a duplicate object key (TS1117) that failed tsc for EVERY spec build on main until a later commit healed it. Second, it ships the persona with no avatar (mascotId 'default', no avatarUrl) — Prue, ticket-improve, and triage-escalations all landed imageless, so the org chart shows blank agents. Both are systemic: any future box-agent build repeats them.",
    what: "The builder's persona-add UPSERTS by key (replace an existing entry, never duplicate it) and AUTO-GENERATES a Nano Banana avatar in the house cast style, uploads it to the agent-avatars bucket, and wires avatarUrl — so every agent persona is unique and has an image.",
    summary: "**Brain refs:** [[../libraries/agents-personas]] [[../integrations/braintree]] [[../recipes/write-a-migration-apply-script]]. Grounded in the 2026-07-07 incidents: the auto-review build's duplicate 'prompt-review' key (TS1117 on src/lib/agents/personas.ts failing every build) + imageless Prue/ticket-improve/triage-escalations. Avatar gen via src/lib/gemini.ts generateNanoBananaProCombine (the same path used to seed the cast) matching the personas.ts AVATAR STYLE. Fix site: the builder's persona-add step (scripts/builder-worker.ts).",
    owner: "platform",
    parent: '[[../functions/platform]] — "Autonomous build platform" mandate: a build that adds an agent persona must upsert it by key (never a duplicate that breaks tsc) and give it an auto-generated avatar (never an imageless agent).',
    blocked_by: [],
    phases: [
      { title: "Phase 1 — upsert persona by key (no duplicate keys)", why: "A duplicate object key is a TS1117 that fails tsc for the whole app, breaking every build — as it did on main.", what: "The builder's persona-add replaces an existing PERSONAS entry with the same key instead of appending a second one.", body: "In the builder persona-add step, before inserting into src/lib/agents/personas.ts, check for an existing entry with the same key and REPLACE it (upsert) rather than appending a duplicate. Cite the persona-add site + personas.ts keying.", verification: "A build that adds a persona whose key already exists replaces the entry (single key, tsc clean), never producing a TS1117 duplicate. A genuinely new key is appended once.", status: "planned" },
      { title: "Phase 2 — auto-generate + attach an avatar", why: "An imageless persona shows blank in the org; every agent should have a real headshot, generated the same way the cast was seeded.", what: "On persona creation the builder generates a Nano Banana headshot in the house AVATAR STYLE, uploads it to the agent-avatars bucket, and sets avatarUrl.", body: "When the builder creates a persona, call generateNanoBananaProCombine (src/lib/gemini.ts) with the personas.ts AVATAR STYLE + a role-appropriate distinctive look, upload to the agent-avatars bucket, and wire avatarUrl (with a ?v=1). Backfill the currently-imageless personas (ticket-improve, and any others). Cite the gemini avatar path + the bucket.", verification: "A newly-built agent persona has a generated avatarUrl pointing at a real bucket image (not mascotId default). The currently-imageless personas are backfilled. Re-running is idempotent (doesn't regenerate an existing avatar).", status: "planned" },
    ],
  }, "planned", { intendedStatusSetBy: "ceo", parentKind: "mandate", parentRef: "platform#build" });
  console.log("builder-persona spec:", b?"authored":"FAILED");
}
main().then(()=>process.exit(0)).catch(e=>{console.error("ERR",e.message||e);process.exit(1);});
