import { loadEnv } from "./_bootstrap";
loadEnv();
import { authorSpecRowStructured } from "../src/lib/author-spec";
const WS = "fdc11e10-b89f-4989-8b73-ed6526c4d906";
async function main() {
  const ok = await authorSpecRowStructured(WS, "cleo-blueprint-product-matching", {
    title: "Cleo blueprint sweep — real category→product matching + dedup by funnel type",
    why: "The shipped blueprint sweep ([[../specs/cleo-lander-blueprint]]) has a Phase-2 punt that broke in production: `pickTargetProduct` blindly picks the FIRST active product for EVERY teardown, so all 12 competitor teardowns (superfood-coffee, longevity, anti-aging, quiz) got blueprinted onto ONE wrong product ('Superfood Tabs' instead of Amazing Coffee), with no dedup — 12 blueprints + 12 Carrie jobs for the wrong thing. The CEO manually cleaned it up and parked the teardowns, but the sweep will re-break the moment new teardowns arrive. It needs to target the RIGHT product per teardown and stop duplicating.",
    what: "Replace the first-active-product heuristic with a category match (the teardown targets the product whose category — its title head-noun like 'Amazing Coffee'→'coffee' — appears in the teardown's brand + recipe strategy + transferable_pattern), skip a teardown that matches NO product in our catalog, and dedup so we create at most one blueprint per (product, funnel_type).",
    summary: "A focused correctness fix to `src/lib/cleo-blueprint.ts`. (1) `pickTargetProduct(workspaceId, teardown)` → match by product category: tokenize each active product's title/handle, and score a product by whether its head-noun (+ other title tokens) appear as whole words in the teardown's text blob (brand + `funnel_type` + `strategy` + `transferable_pattern`); return the best-scoring product, or NULL when nothing scores (skip — we don't sell that category). A superfood-coffee teardown → Amazing Coffee; a longevity/skin teardown → null. (2) In `runCleoBlueprintSweep`, call it PER teardown (not once for the sweep), skip on null, and DEDUP by `(product_id, funnel_type)` — both within the sweep and against existing `lander_blueprints` rows — so we never create 5 advertorial blueprints for the same product. Keep it a pure, unit-testable matcher. After it lands, the CEO un-parks the teardowns (reset growth_reviewed_at) so the corrected sweep re-processes them.",
    owner: "growth",
    parent: "[[../goals/acquisition-research-engine]] — correctness fix so Cleo blueprints the RIGHT product (Growth operates; Ada/Platform builds — [[../functions/platform]]).",
    blocked_by: [],
    phases: [
      { title: "Category product-matching + per-teardown target + dedup", why: "The sweep must target the right product per teardown and not duplicate — the current first-product + no-dedup logic is actively wrong in prod.", what: "Rewrite pickTargetProduct to a category matcher (skip on no match) and make the sweep per-teardown + deduped by (product, funnel_type).", status: "planned",
        body: "In `src/lib/cleo-blueprint.ts`: add a pure `matchProductToTeardown(teardown, products)` — tokenize product title+handle, score by whole-word presence of the product's head-noun (weight 2) + other title tokens (weight 1) in the teardown text blob (`brand` + recipe `funnel_type`/`strategy`/`transferable_pattern`), return highest-scoring product or NULL if zero. Rewrite `pickTargetProduct(workspaceId, teardown)` to load active products once and delegate to it (no teardown arg → back-compat first-product). In `runCleoBlueprintSweep`: fetch active products once, then PER teardown call the matcher — null → mark reviewed + skip ('no product in our catalog matches this category'); else diff vs that product's existing lander types (cache per product) and, on a blueprint decision, DEDUP by `(product_id, funnel_type)` against both a this-sweep set AND existing `lander_blueprints` rows (a new `hasBlueprintForProductType` reader) — skip duplicates. Unit tests pin: a superfood-coffee teardown → Amazing Coffee; a longevity teardown → null; two advertorial teardowns for one product → one blueprint. Probe the products table (database-is-the-spec).",
        verification: "A dry-run over the 12 real parked teardowns (after un-parking) creates blueprints ONLY on category-matching products (the superfood-coffee teardowns → Amazing Coffee; the longevity/anti-aging/quiz ones → skipped, not blueprinted onto a coffee product), and AT MOST ONE blueprint per (product, funnel_type). matchProductToTeardown unit tests pass (coffee→Amazing Coffee, longevity→null, dedup holds). No teardown maps to 'Superfood Tabs' unless its category actually matches. tsc clean." },
      { title: "Brain page update", why: "CLAUDE.md hard rule + the matching rule should be documented on Cleo's blueprint page.", what: "Update the cleo-blueprint brain page with the category-matching + dedup rule.", status: "planned",
        body: "Update `docs/brain/libraries/cleo-blueprint.md` (or the [[../libraries/storefront-optimizer-agent]] blueprint section) with the category-match + skip-on-no-match + dedup-by-funnel-type behavior, replacing the documented Phase-2 first-product punt. brain:index reconcile.",
        verification: "The brain page documents the category matcher + dedup and no longer describes the first-active-product punt. brain:index reconcile clean. tsc clean." },
    ],
  }, "planned", { intendedStatusSetBy: "ceo" });
  console.log(ok ? "authored cleo-blueprint-product-matching" : "author failed");
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
