-- Daily AI Analysis Reports
--
-- Synthesizes a day's worth of ticket_analyses into:
--   1. A short narrative summary
--   2. Themes that surfaced across multiple tickets
--   3. Proposed sonnet_prompts and grader_prompts that the admin can approve
--      to make tomorrow better
--
-- Generated by Opus at 6 AM Central daily (covers the previous day).
-- Also generatable on-demand via the API.

CREATE TABLE IF NOT EXISTS daily_analysis_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  date DATE NOT NULL,

  -- Aggregates (snapshotted from ticket_analyses for this date)
  analyzed_count INTEGER NOT NULL DEFAULT 0,
  avg_score NUMERIC(3,1),
  action_items_count INTEGER NOT NULL DEFAULT 0,
  admin_corrected_count INTEGER NOT NULL DEFAULT 0,
  worst_score INTEGER,
  best_score INTEGER,

  -- LLM-generated narrative + structure
  summary TEXT,
  themes JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- themes: [{ name, count, ticket_ids[], description, severity }]

  recommendations JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- recommendations: [{ priority, description }]

  -- Rule proposals — IDs of rows inserted into sonnet_prompts / grader_prompts
  proposed_sonnet_prompt_ids UUID[] NOT NULL DEFAULT '{}',
  proposed_grader_prompt_ids UUID[] NOT NULL DEFAULT '{}',

  -- Cost tracking
  model TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  cost_cents NUMERIC(10,4),

  -- Metadata
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  generated_by TEXT,
  trigger TEXT NOT NULL DEFAULT 'cron',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(workspace_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_analysis_reports_ws_date
  ON daily_analysis_reports(workspace_id, date DESC);

ALTER TABLE daily_analysis_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "daily_analysis_reports_select" ON daily_analysis_reports
  FOR SELECT TO authenticated
  USING (
    workspace_id IN (
      SELECT workspace_id FROM workspace_members WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "daily_analysis_reports_service" ON daily_analysis_reports
  FOR ALL TO service_role USING (true) WITH CHECK (true);
